# Generated by Django 4.2.11 on 2026-04-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('category', models.CharField(choices=[('digital_marketing', 'Digital Marketing'), ('web_development', 'Web Development'), ('devops', 'DevOps')], max_length=30)),
                ('short_description', models.CharField(help_text='One-line summary shown on the listing page.', max_length=255)),
                ('description', models.TextField(help_text='Full description shown on the detail page.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Starting price in USD.', max_digits=10)),
                ('icon_class', models.CharField(default='bi bi-stars', help_text='Bootstrap Icon class, e.g. "bi bi-graph-up"', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
