# Generated by Django 4.2.11 on 2026-04-02 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('budget_range', models.CharField(choices=[('under_1k', 'Under $1,000'), ('1k_5k', '$1,000 – $5,000'), ('5k_10k', '$5,000 – $10,000'), ('10k_plus', '$10,000+'), ('discuss', "Let's Discuss")], default='discuss', max_length=20)),
                ('project_name', models.CharField(help_text='Short name for this project.', max_length=150)),
                ('project_description', models.TextField(help_text='Describe what you need in detail.')),
                ('deadline', models.DateField(blank=True, help_text='Desired completion date (optional).', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (visible to staff only).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
